EFSemop/efsemop/Models/ViewModels/SubAlcaldia/CreateSubAlcaldiaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace efsemop.Models.ViewModels.SubAlcaldia
{
    public class CreateSubAlcaldiaViewModel
    {
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "Zona es un dato requerido.")]
        [StringLength(190, ErrorMessage = "Ha superado el número de caracteres permitidos")]
        public string Zona { get; set; }
        public string Telefono { get; set; }
        public string NombreSubAlcalde { get; set; }
    }
}

EFSemop/efsemop/Controllers/SubAlcaldiaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using efsemop.Framework.Pepemosca.Data;
using efsemop.Framework.Pepemosca.Domain;
using efsemop.Models.ViewModels.SubAlcaldia;
using PagedList;

namespace efsemop.Controllers
{
    public class SubAlcaldiaController : Controller
    {
        protected readonly IRepoSubAlcaldia RepoSubAlcaldia;
        public SubAlcaldiaController(IRepoSubAlcaldia pRepoSubAlcaldia)
        {
            if (pRepoSubAlcaldia == null)
                throw new ArgumentNullException(nameof(pRepoSubAlcaldia));
            RepoSubAlcaldia = pRepoSubAlcaldia;
        }

        // GET: SubAlcaldia
        public ActionResult Index(string texto, string sortOrder, string currentFilter, int? page)
        {
            var pageSize = 5;
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NombreSortParm = string.IsNullOrEmpty(sortOrder) ? "nombre_desc" : string.Empty;
            ViewBag.ZonaSortParm = sortOrder == "Zona" ? "zona_desc" : "Zona";
            if (!string.IsNullOrWhiteSpace(texto))
            {
                page = 1;
            }
            else
            {
                texto = currentFilter;
            }
            ViewBag.CurrentFilter = texto;
            var pageIndex = (page ?? 1);
            var result = RepoSubAlcaldia.Busqueda(texto, sortOrder, pageIndex, pageSize);
            return View(result);
        }

        // GET: SubAlcaldia/Crear
        public ActionResult Crear()
        {
            return View();
        }

        // POST: SubAlcaldia/Crear
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Crear([Bind(Include = "Nombre,Direccion,Zona,Telefono, NombreSubAlcalde")] CreateSubAlcaldiaViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            var subAlcaldia = new SubAlcaldia()
            {
                Nombre = model.Nombre,
                Direccion = model.Direccion,
                Zona = model.Zona,
                Telefono = model.Telefono,
                NombreSubAlcalde = model.NombreSubAlcalde
            };
            var result = await RepoSubAlcaldia.Crear(subAlcaldia);
            return RedirectToAction("Index");
        }

        // GET: SubAlcaldia/Eliminar/5
        public async Task<ActionResult> Eliminar(int? id, bool? concurrencyError)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subAlcaldia = await RepoSubAlcaldia.Obtener(id.Value);
            if (subAlcaldia == null)
            {
                if (concurrencyError.GetValueOrDefault())
                {
                    return RedirectToAction("Index");
                }
                return HttpNotFound();
            }
            if (concurrencyError.GetValueOrDefault())
            {
                ViewBag.ConcurrencyErrorMessage = "El registro que intentó eliminar fue modificado por otro usuario después de consultar " +
                                                  "los valores originales. " +
                                                  "La operación de eliminación fue cancelada y los valores actuales se han vuelto a " +
                                                  "cargar. Si aún desea eliminar este registro, haga clic en el botón " +
                                                  "Eliminar de nuevo. De lo contrario Haga clic en el hipervínculo Cancelar.";
            }
            return View(subAlcaldia);

        }

        // POST: SubAlcaldia/Eliminar/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Eliminar(SubAlcaldia subAlcaldia)
        {
            try
            {
                var result = await RepoSubAlcaldia.Eliminar(subAlcaldia.IdSubAlcaldia);
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException)
            {
                return RedirectToAction("Eliminar", new { concurrencyError = true, id = subAlcaldia.IdSubAlcaldia });
            }
            catch (DataException)
            {
                //Log the error
                ModelState.AddModelError(string.Empty, "No se puede eliminar. Inténtelo de nuevo, y si el problema persiste pongase con el administrador del sistema.");
                return View(subAlcaldia);
            }
        }

        // GET: SubAlcaldia/Editar/5
        public async Task<ActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subAlcaldia = await RepoSubAlcaldia.Obtener(id.Value);
            if (subAlcaldia == null)
            {
                return HttpNotFound();
            }
            return View(subAlcaldia);
        }

        // POST: SubAlcaldia/Editar/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Editar(int? id, byte[] rowVersion)
        {
            var fieldsToBind = new[] { "Nombre", "Direccion", "Zona", "Telefono", "NombreSubAlcalde" };

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subAlcaldiaToUpdate = await RepoSubAlcaldia.Obtener(id.Value);
            if (subAlcaldiaToUpdate == null)
            {
                var deletedSubAlcaldia = new SubAlcaldia();
                TryUpdateModel(deletedSubAlcaldia, fieldsToBind);
                ModelState.AddModelError(string.Empty, "Imposible guardar los cambios. El elemento fué eliminado por otro usuario.");
                return View(deletedSubAlcaldia);
            }
            if (!TryUpdateModel(subAlcaldiaToUpdate, fieldsToBind)) return View(subAlcaldiaToUpdate);
            try
            {
                var res = await RepoSubAlcaldia.Editar(subAlcaldiaToUpdate);
                //subAlcaldiaToUpdate = res;
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                var entry = ex.Entries.Single();
                var clientValues = (SubAlcaldia)entry.Entity;
                var databaseEntry = entry.GetDatabaseValues();
                if (databaseEntry == null)
                {
                    ModelState.AddModelError(string.Empty, "Imposible guardar los cambios. El elemento fué eliminado por otro usuario.");
                }
                else
                {
                    var databaseValues = (SubAlcaldia)databaseEntry.ToObject();

                    if (databaseValues.Nombre != clientValues.Nombre)
                        ModelState.AddModelError("Nombre", "Nombre valor: "
                                                           + databaseValues.Nombre);
                    if (databaseValues.Direccion != clientValues.Direccion)
                        ModelState.AddModelError("Direccion", "Direccion valor: "
                                                              + databaseValues.Nombre);
                    if (databaseValues.Zona != clientValues.Zona)
                        ModelState.AddModelError("Zona", "Zona valor: "
                                                         + databaseValues.Zona);
                    if (databaseValues.Telefono != clientValues.Telefono)
                        ModelState.AddModelError("Telefono", "Telefono valor: "
                                                             + databaseValues.Telefono);
                    if (databaseValues.NombreSubAlcalde != clientValues.NombreSubAlcalde)
                        ModelState.AddModelError("NombreSubAlcalde", "NombreSubAlcalde valor: "
                                                                     + databaseValues.NombreSubAlcalde);
                    ModelState.AddModelError(string.Empty, "El registro que está intentado modificar, fue eliminado por otro usuario después de consultar " +
                                                      "los valores originales. La operación de edición fue cancelada.");
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError(string.Empty, "No se puede editar. Inténtelo de nuevo, y si el problema persiste pongase con el administrador del sistema.");
            }

            return View(subAlcaldiaToUpdate);
        }

    }
}

EFSemop/efsemop/Views/SubAlcaldia/Crear.cshtml
@using System.Web.Optimization
@model efsemop.Models.ViewModels.SubAlcaldia.CreateSubAlcaldiaViewModel

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sub Alcaldia</h4>

        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "Nombre es un dato requerido.", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "Direccion es un dato requerido.", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zona, string.Empty , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "Telefono es un dato requerido.", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreSubAlcalde, "Nombre Sub Alcalde", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreSubAlcalde, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreSubAlcalde, "Nombre Sub Alcalde es un dato requerido.", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancelar", "Index")
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

}

EFSemop/efsemop/Views/SubAlcaldia/Editar.cshtml
@using System.Web.Optimization
@model efsemop.Framework.Pepemosca.Data.SubAlcaldia

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sub Alcaldía</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.IdSubAlcaldia)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "Nombre es un dato requerido.", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "Direccion es un dato requerido", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zona, "Zona es un dato requerido", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "Telefono es un dato requerido.", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NombreSubAlcalde, "Nombre Sub Alcalde", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreSubAlcalde, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreSubAlcalde, "Nombre Sub Alcalde es un dato requerido.", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancelar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EFSemop/efsemop/Views/SubAlcaldia/Eliminar.cshtml
@model efsemop.Framework.Pepemosca.Data.SubAlcaldia

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<p class="error">@ViewBag.ConcurrencyErrorMessage</p>

<h3>Está seguro de eliminar el elemento?</h3>
<div>
    <h4>Sub Alcaldia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Responsable
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreSubAlcalde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.IdSubAlcaldia)
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Cancelar", "Index")
        </div>
    }
</div>

EFSemop/efsemop/Views/SubAlcaldia/Index.cshtml
@using System.Web.Optimization
@model PagedList.IPagedList<efsemop.Framework.Pepemosca.Data.SubAlcaldia>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Sub Alcaldias";
}

@section Styles {
    @Styles.Render("~/bundles/core/subalcaldia/css")

}

<h3>@ViewBag.Title</h3>

<div id="page-subalcaldias">

    <div class="row">
        <div class="col-xs-9 col-sm-3 spacer-component">
            <div class="input-group">
                <p>
                    @Html.ActionLink("Crear Nuevo", "Crear")
                </p>
            </div>
            <div class="clearfix"></div>
            @using (Html.BeginForm("Index", "SubAlcaldia", FormMethod.Get))
            {
                <div class="input-group">
                    @Html.TextBox("texto", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "Texto búsqueda..." })
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Buscar</button>
                    </span>
                </div>
            }
        </div>
    </div>


    <div class="row">
        <div class="col-md-12 col-xs-12">
            <table id="tbl-subalcaldias" class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>@Html.ActionLink("Nombre", "Index", new { sortOrder = ViewBag.NombreSortParm, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>Direccion</th>
                        <th>@Html.ActionLink("Zona", "Index", new { sortOrder = ViewBag.ZonaSortParm, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>Telefono</th>                        
                        <th>Responsable</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Direccion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Zona)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telefono)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NombreSubAlcalde)
                            </td>
                            <td>
                                <div id="box-opciones" class="btn-group">
                                    <button class="btn btn-primary btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="glyphicon glyphicon glyphicon-th-list" aria-hidden="true"></span>
                                    </button>
                                    <ul id="btn-opciones" class="dropdown-menu">
                                        <li>
                                            <a href="@Url.Action("Editar", "SubAlcaldia", new {id = item.IdSubAlcaldia})"><i class="glyphicon glyphicon glyphicon-edit"> </i> Editar </a>
                                            <a href="@Url.Action("Eliminar", "SubAlcaldia", new {id = item.IdSubAlcaldia})"><i class="glyphicon glyphicon glyphicon-remove"> </i> Eliminar </a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <br />
            Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("Index",
           new
           {
               page,
               sortOrder = ViewBag.CurrentSort,
               currentFilter = ViewBag.CurrentFilter
           }))
        </div>
    </div>

</div>